def build_rate(amount_original: object, amount_base: object, currency: str) -> float: ...
def cashflow_sum(db_path: str, record_type: str, start_date: str, end_date: str) -> float: ...
def currency_default_rates_for_base(
    base_currency: str, rates: dict[str, float]
) -> dict[str, float]: ...
def currency_rate_for(currency: str, base_currency: str, rates: dict[str, float]) -> float: ...
def currency_resolve_provider_order(
    base_currency: str,
    provider_mode: str,
    primary_provider: str,
    fallback_provider: str,
    commercial_fallback_provider: str,
    enable_cbr: bool,
    provider_order: list[str] | None = None,
) -> list[str]: ...
def metrics_burn_rate(db_path: str, start_date: str, end_date: str, days: int) -> float: ...
def metrics_income_by_category(
    db_path: str, start_date: str, end_date: str, limit: int | None = None
) -> list[dict[str, object]]: ...
def metrics_monthly_summary(
    db_path: str, start_date: str | None = None, end_date: str | None = None
) -> list[dict[str, object]]: ...
def metrics_period_snapshot(
    db_path: str,
    start_date: str,
    end_date: str,
    days: int,
    category_limit: int | None = None,
    tag_limit: int | None = None,
) -> dict[str, object]: ...
def metrics_period_snapshot_compact(
    db_path: str,
    start_date: str,
    end_date: str,
    days: int,
    category_limit: int | None = None,
    tag_limit: int | None = None,
) -> tuple[
    float,
    float,
    list[tuple[str, float, int]],
    list[tuple[str, float, int]],
    list[tuple[str, str, float, int]],
    tuple[int, int, float],
    list[tuple[str, float, float, float, float]],
    list[tuple[str, float, float, float]],
]: ...
def metrics_refresh_snapshot_compact(
    db_path: str,
    start_date: str,
    end_date: str,
    days: int,
    category_limit: int | None = None,
    tag_limit: int | None = None,
) -> tuple[
    float,
    float,
    list[tuple[str, float, int]],
    list[tuple[str, float, int]],
    list[tuple[str, str, float, int]],
    list[tuple[str, float, float, float, float]],
]: ...
def metrics_savings_rate(db_path: str, start_date: str, end_date: str) -> float: ...
def metrics_spending_by_category(
    db_path: str, start_date: str, end_date: str, limit: int | None = None
) -> list[dict[str, object]]: ...
def metrics_spending_by_tag(
    db_path: str, start_date: str, end_date: str, limit: int | None = None
) -> list[dict[str, object]]: ...
def metrics_tag_coverage(db_path: str, start_date: str, end_date: str) -> dict[str, object]: ...
def record_get_row(db_path: str, record_id: int) -> dict[str, object] | None: ...
def record_list_rows(
    db_path: str,
) -> list[dict[str, object]]: ...
def record_rows_by_tag(db_path: str, tag_name: str) -> list[dict[str, object]]: ...
def timeline_cumulative_income_expense(db_path: str) -> list[dict[str, object]]: ...
def timeline_monthly_cashflow(
    db_path: str, start_date: str | None = None, end_date: str | None = None
) -> list[dict[str, object]]: ...
def timeline_net_worth_monthly_deltas(db_path: str) -> list[dict[str, object]]: ...
def convert_amount(amount: float, rate: float) -> float: ...
def calculate_daily_burn(total_spent: float, days_passed: int) -> float: ...
def mandatory_expense_row(db_path: str, expense_id: int) -> dict[str, object] | None: ...
def mandatory_expense_rows(db_path: str) -> list[dict[str, object]]: ...
def minor_to_money(value: object) -> float: ...
def money_diff_text(left: object, right: object) -> str: ...
def money_abs(value: object) -> float: ...
def quantize_money_text(value: object) -> str: ...
def quantize_rate_text(value: object) -> str: ...
def rate_diff_text(left: object, right: object) -> str: ...
def rate_to_text(value: object) -> str: ...
def to_minor_units(value: object) -> int: ...
def to_money_float(value: object) -> float: ...
def to_rate_float(value: object) -> float: ...
def transfer_id_by_record_index(db_path: str, index: int) -> int | None: ...
def transfer_list_rows(db_path: str) -> list[dict[str, object]]: ...
def wallet_balance_parts(
    db_path: str, wallet_id: int, up_to_date: str | None = None
) -> tuple[float, str, float] | None: ...
def wallet_balance_rows(
    db_path: str, up_to_date: str | None = None
) -> list[tuple[int, str, str, float, float]]: ...
def wallet_list_rows(db_path: str) -> list[dict[str, object]]: ...
def storage_clear_read_cache() -> None: ...
