from __future__ import annotations

from collections.abc import Iterator
from contextlib import AbstractContextManager
from typing import Any, Protocol, runtime_checkable

from domain.asset import Asset, AssetSnapshot
from domain.debt import Debt, DebtPayment
from domain.goal import Goal
from domain.records import MandatoryExpenseRecord, Record
from domain.transfers import Transfer
from domain.wallets import Wallet


@runtime_checkable
class SchemaMetaRepository(Protocol):
    def get_schema_meta(self, key: str) -> str | None: ...

    def set_schema_meta(self, key: str, value: str) -> None: ...


@runtime_checkable
class SqlQueryRepository(Protocol):
    def query_all(self, sql: str, params: tuple = ()) -> list[Any]: ...

    def query_one(self, sql: str, params: tuple = ()) -> Any: ...

    def query_iter(
        self,
        sql: str,
        params: tuple = (),
        *,
        chunk_size: int = 1000,
    ) -> Iterator[Any]: ...


@runtime_checkable
class SqlMutationRepository(SqlQueryRepository, Protocol):
    def execute(self, sql: str, params: tuple = ()) -> None: ...

    def commit(self) -> None: ...

    def transaction(self) -> AbstractContextManager[Any]: ...

    def set_sqlite_sequence(self, table: str, seq: int | None = None) -> None: ...


@runtime_checkable
class AssetRepositoryProtocol(SqlMutationRepository, Protocol):
    def save_asset(self, asset: Asset) -> None: ...

    def get_asset_by_id(self, asset_id: int) -> Asset: ...

    def deactivate_asset(self, asset_id: int) -> bool: ...

    def save_asset_snapshot(self, snapshot: AssetSnapshot, *, commit: bool = True) -> None: ...

    def load_assets(self, *, active_only: bool = False) -> list[Asset]: ...

    def load_asset_snapshots(self, asset_id: int | None = None) -> list[AssetSnapshot]: ...

    def get_latest_asset_snapshots(self, *, active_only: bool = True) -> list[AssetSnapshot]: ...


@runtime_checkable
class GoalRepositoryProtocol(SqlMutationRepository, Protocol):
    def save_goal(self, goal: Goal) -> None: ...

    def get_goal_by_id(self, goal_id: int) -> Goal: ...

    def delete_goal(self, goal_id: int) -> bool: ...

    def load_goals(self) -> list[Goal]: ...


@runtime_checkable
class BudgetRepositoryProtocol(SqlMutationRepository, Protocol):
    pass


@runtime_checkable
class DebtRepositoryProtocol(SqlMutationRepository, Protocol):
    def get_debt_by_id(self, debt_id: int) -> Debt: ...

    def load_debts(self) -> list[Debt]: ...

    def save_debt(self, debt: Debt) -> None: ...

    def save_debt_payment(self, payment: DebtPayment) -> None: ...

    def get_debt_payment_by_id(self, payment_id: int) -> DebtPayment: ...

    def load_debt_payments(self, debt_id: int | None = None) -> list[DebtPayment]: ...

    def delete_debt(self, debt_id: int) -> bool: ...

    def delete_debt_payment(self, payment_id: int) -> bool: ...

    def save(self, record: Record) -> None: ...

    def load_all(self) -> list[Record]: ...

    def delete_by_index(self, index: int) -> bool: ...

    def load_wallets(self) -> list[Wallet]: ...


@runtime_checkable
class DistributionRepositoryProtocol(SqlMutationRepository, Protocol):
    pass


@runtime_checkable
class AuditRepositoryProtocol(SqlQueryRepository, Protocol):
    @property
    def db_path(self) -> str: ...

    def foreign_key_issues(self) -> list[Any]: ...

    def has_system_wallet_row(self) -> bool: ...

    def load_all(self) -> list[Record]: ...

    def load_transfers(self) -> list[Transfer]: ...

    def load_wallets(self) -> list[Wallet]: ...

    def load_mandatory_expenses(self) -> list[MandatoryExpenseRecord]: ...

    def load_debts(self) -> list[Debt]: ...

    def load_debt_payments(self, debt_id: int | None = None) -> list[DebtPayment]: ...
