def build_rate(amount_original: object, amount_base: object, currency: str) -> float: ...
def convert_amount(amount: float, rate: float) -> float: ...
def calculate_daily_burn(total_spent: float, days_passed: int) -> float: ...
def minor_to_money(value: object) -> float: ...
def money_abs(value: object) -> float: ...
def to_minor_units(value: object) -> int: ...
def to_money_float(value: object) -> float: ...
def to_rate_float(value: object) -> float: ...
